// <auto-generated />
namespace TaskQuest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091652160_2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
